apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-webhook-feishu.fullname" . }}
  labels:
    {{- include "prometheus-webhook-feishu.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- toPrettyJson .Values.config | nindent 4 }}
