{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-webhook-feishu.serviceAccountName" . }}
  labels:
    {{- include "prometheus-webhook-feishu.labels" . | nindent 4 }}
{{- end }}
